#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          4
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a minecraft state=floating
bspc rule -a Emacs state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a idea state=floating

# kill already open services that cause issues on re-executing
killall dunst
killall volumeicon

# startups
wmname LG3D
picom &
dunst &
~/.config/polybar/launch.sh &
nm-applet &
fcitx5 &
lxsession &
emacs --daemon &
volumeicon &
wal -i ~/Pictures/Wallpapers/ --backend (random choice haishoku schemer)
